# Generated by Django 5.1.4 on 2025-01-07 10:54

from random import randint
import django.db.models.deletion
from django.db import migrations, models
import factory


def forward_function(app, schema):
    Site = app.get_model("sites", "Site")
    Farmer = app.get_model("sites", "Farmer")

    class FarmerFactory(factory.django.DjangoModelFactory):
        first_name = factory.Faker("first_name")
        last_name = factory.Faker("last_name")

        class Meta:
            model = Farmer

    class SiteFactory(factory.django.DjangoModelFactory):
        name = factory.Faker("city")
        farmer = factory.SubFactory(FarmerFactory)

        class Meta:
            model = Site

    [SiteFactory() for _ in range(randint(5, 10))]


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sites.farmer"
                    ),
                ),
            ],
        ),
        migrations.RunPython(forward_function, migrations.RunPython.noop),
    ]
